services:
  app:
    build: .
    
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://appuser:apppassword@mongodb:27017/mydb
    volumes: 
      - .:/app #for Development
    depends_on:
      - mongodb
    networks:
      - app-network
    command: ["npm", "run", "dev"] #For development 
  
  mongodb:
    image: mongo:8.2.7
    container_name: mongodb

    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mydb

    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js

    networks:
      - app-network
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Public:/usr/share/nginx/html:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data: